spring:
  mail:
    host: <smtp-server-address>
    port: <smtp-server-port: probably 587>
    username: <username>
    password: <password>
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb://mongoawf/awf
  session:
    type:
      store-type: mongo
