spring:
  mail:
    host: <smtp-server-address>
    port: <smtp-server-port: probably 587>
    username: <username>
    password: <password>
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb://mongoawf/awf
  session:
    type:
      store-type: mongo
security:
  oauth2:
    client:
      id: <identifier for oauth2 server - e.g. MicrosoftOnline, Git, Facebook, etc>
      clientId: <client id>
      clientSecret: <client secret>
      accessTokenUri: <e.g. https://login.microsoftonline.com/common/oauth2/v2.0/token>
      userAuthorizationUri: <e.g. https://login.microsoftonline.com/common/oauth2/v2.0/authorize>
      clientAuthenticationScheme: form
      scope: openid,files.readwrite,offline_access,user.read
    resource:
      userInfoUri: <e.g. https://graph.microsoft.com/v1.0/me>
app:
  admin:
    domain: <domain for admin users - e.g. "@example.com">
